
logging:
  level:
    net.flyingfishflash.ledger: DEBUG
    #ROOT: DEBUG
    #org.thymeleaf: TRACE
    #org.springframework.boot: TRACE

spring:
  profiles:
    active: dev-postgresql
  thymeleaf:
    cache: false #enable in production


---

spring:
  profiles: dev-h2

  jpa:
    hibernate:
      ddl-auto: drop-create
    show-sql: true

  h2:
    console:
      enabled: true 

  datasource:
    url: jdbc:h2:mem:ledger-concept;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

---

spring:
  profiles: dev-postgresql

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
        hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  datasource:
    url: jdbc:postgresql://localhost:5432/ledger-concept
    username: gregory
    password: 
    platform: POSTGRESQL
  