kind: pipeline
type: docker
name: default

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: publish feature branch
    image: plugins/docker
    settings:
      auto_tag: false
      repo: registry.flyingfishflash.net/flyingfishflash/ledger
      tags:
        - "${DRONE_COMMIT_BRANCH}"
    when:
      branch:
        exclude:
          - master
      event:
        exclude:
          - tag

  - name: publish master branch
    image: plugins/docker
    settings:
      auto_tag: true
      repo: registry.flyingfishflash.net/flyingfishflash/ledger

trigger:
  event:
    - push
    - tag


