kind: pipeline
type: docker
name: default

steps:
  - name: fetch git tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: generate docker tags
    image: gradle:6.6-jdk14
    commands:
      - chmod +x drone-generate-docker-tags.sh
      - echo -n $(./drone-generate-docker-tags.sh) > .tags
      - if [ "${DRONE_COMMIT_BRANCH}" = "master" ] ; then echo ",latest" >> .tags ; fi
      - cat .tags

  - name: publish feature branch
    image: plugins/docker
    settings:
      auto_tag: false
      repo: registry.flyingfishflash.net/flyingfishflash/ledger
    when:
      branch:
        exclude:
          - master
      event:
        exclude:
          - tag

  - name: publish master branch
    image: plugins/docker
    settings:
      auto_tag: false
      repo: registry.flyingfishflash.net/flyingfishflash/ledger
    when:
      branch:
        include:
          - master

trigger:
  event:
    - push
    - tag


