before_script:
  - pwd
  - cd ..
  - git clone -b custom --single-branch https://github.com/rollenwiese/nestedj.git
  - cd nestedj
  - mvn -q clean package
  - mvn -q --batch-mode --show-version install:install-file -Dfile=target/NestedJ-3.0.0.RELEASE.jar -DpomFile=pom.xml
  - ls -l target/
  - cd ledger

stages:
  - build

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn -q clean package -B"
  artifacts:
    paths:
      - target/*.jar
    expire_in: 10 minutes
