# goreleaser configuration
builds:
  -
    skip: true
checksum:
  disable: true
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
release:
  github:
env_files:
#  gitea_token: ~/.config/goreleaser/gitea/gitea_token
  github_token: ~/.config/goreleaser/github/github_token
#  gitlab_token: ~/.config/goreleaser/gitlab/gitlab_token
