FROM openjdk:14-jdk-alpine
VOLUME /tmp
EXPOSE 8181
RUN mkdir /app
#RUN apt-get update && apt-get -y upgrade && apt-get -y install curl
COPY ./build/libs/ledger.jar /app/ledger.jar
ENV JDK_JAVA_OPTIONS=""
ENTRYPOINT exec java -jar /app/ledger.jar
