version: "3.8"

services:

  ledger-backend:
    container_name: ledger-backend
    depends_on:
      - ledger-postgres
    environment:
#      The value of API_SERVER will be used to generate the resources/static/assets/config.json file
#      config.json is fetched by api clients
#      Defaults to: http://localhost:8181)
#      API_SERVER: http://dockerhost:52300
#      If behind a proxy like traefik with a DNS name configured:
#      API_SERVER: ledger-backend.mydomain.tld
      API_SERVER: http://localhost:53200
      JDK_JAVA_OPTIONS: >
        -Djava.security.egd=file:/dev/./urandom
        -Duser.timezone="UTC"
      SPRING_PROFILES_ACTIVE: postgresql
      SPRING_JPA_SHOW_SQL: 'false'
      SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-postgres:5432/ledger
      SPRING_DATASOURCE_USERNAME: ledger
      SPRING_DATASOURCE_PASSWORD: ledger
      SPRING_DATASOURCE_PLATFORM: POSTGRESQL
#      SPRING_PROFILES_ACTIVE: h2
#      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: 'true'
#      SPRING_DATASOURCE_PLATFORM: 'POSTGRESQL'
#      SPRING_DATASOURCE_URL: jdbc:h2:mem:ledger;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;DATABASE_TO_LOWER=true;MODE=PostgreSQL
#      SPRING_DATASOURCE_USERNAME: ledger
#      SPRING_DATASOURCE_PASSWORD:
#      http://docker-host:8181/h2-console
    healthcheck:
      test: "wget http://127.0.0.1:8181/actuator/info -T 30 -q -O -"
      interval: "60s"
      timeout: "5s"
      start_period: "15s"
      retries: 3
    image: registry.gitlab.com/rollenwiese/ledger:backend-development
    logging:
      driver: journald
      options:
        tag: docker/ledger
    networks:
      - default
    ports:
      - "52300:8181"
    restart: unless-stopped

  ledger-frontend:
    container_name: ledger-frontend
    depends_on:
      - ledger-backend
    environment:
      UPSTREAM_SERVER: 'ledger-backend:8181'
    image: registry.gitlab.com/rollenwiese/ledger:frontend-development
    logging:
      driver: journald
      options:
        tag: docker/ledger_frontend
    networks:
      - default
    ports:
      - "52301:80"
    restart: unless-stopped

  ledger-postgres:
    container_name: ledger-postgres
    environment:
      - POSTGRES_USER=ledger
      - POSTGRES_PASSWORD=ledger
      - POSTGRES_DB=ledger
    image: index.docker.io/postgres:latest
    logging:
      driver: journald
      options:
        tag: docker/ledger_postgres
    networks:
      - default
    ports:
      - "52302:5432"
    restart: unless-stopped

networks:

  default:
