---
builds:
- skip: true
checksum:
  disable: true
changelog:
  sort: "asc"
  filters:
    exclude:
    - "Merge pull request"
    - "Merge branch"
release:
  github: null
env_files:
  github_token: "~/.config/goreleaser/github/github_token"
