---
builds:
- skip: true
checksum:
  disable: true
changelog:
  sort: "asc"
  filters:
    exclude:
    - "Merge pull request"
    - "Merge branch"
release:
  gitlab:
    owner: "flyingfishflash"
    name: "ledger"
env_files:
  gitlab_token: "~/.config/goreleaser/gitlab/gitlab_token"
