---
before:
  hooks: null
builds:
- skip: true
archives: null
checksum:
  disable: true
changelog:
  sort: "asc"
  filters:
    exclude:
    - "Merge pull request"
    - "Merge branch"
release:
  gitea:
    owner: "flyingfishflash"
    name: "ledger"
gitea_urls:
  api: "https://codeberg.org/api/v1/"
  download: "https://codeberg.org"
env_files:
  gitea_token: "~/.config/goreleaser/codeberg/codeberg_token"
