# goreleaser configuration
before:
  hooks:
builds:
  -
    skip: true
archives:
checksum:
  disable: true
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
release:
  gitea:
    owner: flyingfishflash
    name: ledger
gitea_urls:
  api: https://gitea.flyingfishflash.net/api/v1/
  download: https://gitea.flyingfishflash.net
env_files:
  gitea_token: ~/.config/goreleaser/gitea/gitea_token
#  github_token: ~/.config/goreleaser/github/github_token
#  gitlab_token: ~/.config/goreleaser/gitlab/gitlab_token
