---

config:
  application:
    name: &application-name "Ledger"
    description: &application-description "A Java based bookkeeping engine and API server"
    documentation: "https://ledger.wiki.github.org/docs"
    api-v1-url-path: &api-v1-url-path "/api/v1"

debug: "false"

logging:
  level:
    org:
      flywaydb: info
      hibernate: info
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: *api-v1-url-path
      cors:
        allowed-origins: "*"
        allowed-methods: "OPTIONS, GET"
      exposure:
        include: "info,health"

server:
  error:
    whitelabel:
      enabled: "false"
  port: "8181"
  servlet:
    session:
      cookie:
        secure: "true"
        http-only: "true"
      timeout: "5m"
  tomcat:
    remoteip:
      protocol-header: "x-forwarded-proto"
      remote-ip-header: "x-forwarded-for"

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: 'false'
#      write-enums-to-lowercase: true
  jpa:
    hibernate:
      ddl-auto: "none"
      # https://stackoverflow.com/questions/29087626/entity-class-name-is-transformed-into-sql-table-name-with-underscores
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        cache:
          use_second_level_cache: "false"
        format_sql: "false"
        generate_statistics: "false"
        jdbc:
          batch_size: "20"
        order_inserts: "true"
        query:
          plan_cache_max_size: "16"
          plan_parameter_metadata_max_size: "32"
      jakarta:
        persistence:
          sharedCache:
            mode: "UNSPECIFIED"
    show-sql: "false"
  main:
    banner-mode: "off"
  mvc:
    throw-exception-if-no-handler-found: "true"
  output:
    ansi:
      enabled: "always"
  profiles:
    active: "h2"
  servlet:
    multipart:
      max-file-size: "50MB"
      max-request-size: "50MB"
  session:
    jdbc:
      initialize-schema: "never"
      table-name: "public.SPRING_SESSION"
  sql:
    init:
      mode: "never"

trace: "false"

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1
    operationsSorter: "alpha"
    tagsSorter: "alpha"
