---

spring:
  config:
    activate:
      on-profile: "h2"
  datasource:
    username: "sa"
    url: "jdbc:h2:mem:ledger;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;DATABASE_TO_LOWER=true;MODE=PostgreSQL"
    password: ""
  h2:
    console:
      enabled: "true"
      settings:
        web-allow-others: "true"
