create table common.user_roles (User_id int8 not null, roles varchar(255))
create table common.users (id int8 generated by default as identity, accountNonExpired boolean not null, accountNonLocked boolean not null, credentialsNonExpired boolean not null, email varchar(255), enabled boolean not null, firstName varchar(255), lastName varchar(255), password varchar(255), username varchar(255), primary key (id))
alter table if exists common.users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username)
alter table if exists common.users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email)
create sequence hibernate_sequence start 1 increment 1
create table Account (id int8 not null, category varchar(255), code varchar(255), currency varchar(255), description varchar(2048), discriminator varchar(255) not null, guid varchar(255), hidden boolean, longName varchar(4096), name varchar(255), normalBalance varchar(255), note varchar(4096), parentId int8, placeholder boolean, taxRelated boolean, treeLeft int8 not null, treeLevel int8 not null, treeRight int8 not null, type varchar(255), commodity_id int8, primary key (id))
create table commodity (id int8 not null, cusip varchar(9), custom_identifier varchar(255), fraction int4, fullname varchar(255), guid varchar(32), mnemonic varchar(255), namespace varchar(255), quote_remote boolean, quote_remote_source varchar(255), primary key (id))
create table Entry (id int8 not null, action varchar(255), enterDate timestamp, guid varchar(32), memo varchar(255), quantity numeric(38, 18), quantitySigned numeric(38, 18), type varchar(255), value_currency varchar(3), value numeric(38, 18), valueSigned numeric(38, 18), account_id int8, transaction_id int8, primary key (id))
create table price (id int8 not null, currency varchar(3), date timestamp, denominator int8, guid varchar(32), numerator int8, price numeric(38, 18), source varchar(255), type varchar(255), commodity_id int8, primary key (id))
create table Transaction (id int8 not null, currency varchar(255), description varchar(255), enterDate timestamp, guid varchar(32), num varchar(255), postDate date, primary key (id))
alter table if exists Account add constraint UK_b8ni42e71dt1qgqjb3ckhgjif unique (guid)
alter table if exists commodity add constraint UK24b8i4dwv69a3as6awua557qi unique (namespace, mnemonic)
alter table if exists commodity add constraint UK_5h06bvsvpygdgk8bxf401wabs unique (guid)
alter table if exists Entry add constraint UK_ptn783mnosq9f073r9ge73rxj unique (guid)
alter table if exists price add constraint UK_5mqd98oonadf0he7i89uxp1y6 unique (guid)
alter table if exists Transaction add constraint UK_q4mn08k5kuq6f068r3eih9jan unique (guid)
alter table if exists common.user_roles add constraint FKo9p66oat9vitrwq4fguhy913q foreign key (User_id) references common.users
alter table if exists Account add constraint FKidplamno3s5a11powxa01du30 foreign key (commodity_id) references commodity
alter table if exists Entry add constraint FKnm67w3rwmwwxnen68x0mkhdsw foreign key (account_id) references Account
alter table if exists Entry add constraint FKewxeplulllji2pr2lify6o4b2 foreign key (transaction_id) references Transaction
alter table if exists price add constraint FK6vykrtjniu94rso0xjs0f2q4n foreign key (commodity_id) references commodity
