version: "3.9"

services:

  ledger-backend:
    container_name: ledger-backend
    depends_on:
      - ledger-postgres
    environment:
      JDK_JAVA_OPTIONS: >
        -Djava.security.egd=file:/dev/./urandom
        -Duser.timezone="UTC"
      SPRING_PROFILES_ACTIVE: postgresql
      SPRING_JPA_SHOW_SQL: 'false'
      SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-postgres:5432/ledger
      SPRING_DATASOURCE_USERNAME: ledger
      SPRING_DATASOURCE_PASSWORD: ledger
      SPRING_DATASOURCE_PLATFORM: POSTGRESQL
#      SPRING_PROFILES_ACTIVE: h2
#      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: 'true'
#      SPRING_DATASOURCE_PLATFORM: 'POSTGRESQL'
#      SPRING_DATASOURCE_URL: jdbc:h2:mem:ledger;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;DATABASE_TO_LOWER=true;MODE=PostgreSQL
#      SPRING_DATASOURCE_USERNAME: ledger
#      SPRING_DATASOURCE_PASSWORD:
#      http://docker-host:8181/h2-console
    healthcheck:
      test: "wget http://127.0.0.1:8181/api/v1/ledger/actuator/info -T 30 -q -O -"
      interval: "60s"
      timeout: "5s"
      start_period: "15s"
      retries: 3
    image: registry.gitlab.com/flyingfishflash/ledger:backend-latest
    logging:
      driver: journald
      options:
        tag: docker/ledger
    networks:
      - default
    ports:
      - "52300:8181"
    restart: unless-stopped

  ledger-frontend:
    container_name: ledger-frontend
    depends_on:
      - ledger-backend
    environment:
      UPSTREAM_SERVER: 'ledger-backend:8181'
#      If the application endpoint is proxied (traefik, etc) set the below environment variable to your URI
#      API_SERVER_URL=https://ledger.my-domain.tld \
#      If the application endpoint isn't proxied, set the below environment variable to include the external port
#      API_SERVER_URL=http://localhost:53111 \
#      Otherwise, the default value of API_SERVER_URL is http://localhost:8181
      API_SERVER_URL: http://localhost:53200
    image: registry.gitlab.com/flyingfishflash/ledger:frontend-latest
    logging:
      driver: journald
      options:
        tag: docker/ledger_frontend
    networks:
      - default
    ports:
      - "52301:80"
    restart: unless-stopped

  ledger-postgres:
    container_name: ledger-postgres
    environment:
      - POSTGRES_USER=ledger
      - POSTGRES_PASSWORD=ledger
      - POSTGRES_DB=ledger
    image: index.docker.io/postgres:latest
    logging:
      driver: journald
      options:
        tag: docker/ledger_postgres
    networks:
      - default
    ports:
      - "52302:5432"
    restart: unless-stopped

networks:

  default:
